{% set name = "bxa" %}
{% set version = "4.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6f301436182bef6a6c4b6fcea4a3f2a0ce4c9f520c8e7bf9e6e144e1756d6c06

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - matplotlib-base
    - ultranest
    - h5py
    - tqdm
    - joblib
    - astropy
    - scipy

test:
  imports:
    - bxa

about:
  home: https://johannesbuchner.github.io/BXA/
  license: GPL3
  license_family: GPL
  license_file: LICENSE
  summary: BXA enables nested sampling in the X-ray spectral analysis environments Xspec/Sherpa for Bayesian Parameter Estimation and Model comparison.

  description: |
    Bayesian X-ray Analysis (BXA) allows reliable parameter inference and model comparison in X-ray astronomy.

    BXA connects the nested sampling algorithms MultiNest and UltraNest to the X-ray spectral analysis environments 
    Xspec (https://heasarc.gsfc.nasa.gov/xanadu/xspec/) and Sherpa (http://cxc.cfa.harvard.edu/sherpa/).

    This allows reliable and automatic Bayesian parameter estimation and model comparison.

  doc_url: https://johannesbuchner.github.io/BXA/
  dev_url: https://github.com/JohannesBuchner/BXA/

extra:
  recipe-maintainers:
    - JohannesBuchner
