{% set name = "bxa" %}
{% set version = "5.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c95c1c59c2e64b2425378383f809de96406243fd959b97f7044fe076c680fc43

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
  host:
    - setuptools
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - matplotlib-base
    - ultranest
    - h5py
    - tqdm
    - joblib
    - astropy-base
    - scipy
    - requests

test:
  requires:
    - python {{ python_min }}
  imports:
    - bxa

about:
  home: https://johannesbuchner.github.io/BXA/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: BXA enables nested sampling in the X-ray spectral analysis environments Xspec/Sherpa for Bayesian Parameter Estimation and Model comparison.

  description: |
    Bayesian X-ray Analysis (BXA) allows reliable parameter inference and model comparison in X-ray astronomy.

    BXA connects the nested sampling algorithms MultiNest and UltraNest to the X-ray spectral analysis environments 
    Xspec (https://heasarc.gsfc.nasa.gov/xanadu/xspec/) and Sherpa (http://cxc.cfa.harvard.edu/sherpa/).

    This allows reliable and automatic Bayesian parameter estimation and model comparison.

  doc_url: https://johannesbuchner.github.io/BXA/
  dev_url: https://github.com/JohannesBuchner/BXA/

extra:
  recipe-maintainers:
    - JohannesBuchner
