{% set name = "bxa" %}
{% set version = "4.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ca6f5cfeba2588dd89e3433db13b0c7e23f679d3de1c85aa0f5490be368e4106

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
  host:
    - setuptools
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - matplotlib-base
    - ultranest
    - h5py
    - tqdm
    - joblib
    - astropy-base
    - scipy
    - requests

test:
  imports:
    - bxa

about:
  home: https://johannesbuchner.github.io/BXA/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: BXA enables nested sampling in the X-ray spectral analysis environments Xspec/Sherpa for Bayesian Parameter Estimation and Model comparison.

  description: |
    Bayesian X-ray Analysis (BXA) allows reliable parameter inference and model comparison in X-ray astronomy.

    BXA connects the nested sampling algorithms MultiNest and UltraNest to the X-ray spectral analysis environments 
    Xspec (https://heasarc.gsfc.nasa.gov/xanadu/xspec/) and Sherpa (http://cxc.cfa.harvard.edu/sherpa/).

    This allows reliable and automatic Bayesian parameter estimation and model comparison.

  doc_url: https://johannesbuchner.github.io/BXA/
  dev_url: https://github.com/JohannesBuchner/BXA/

extra:
  recipe-maintainers:
    - JohannesBuchner
